config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tirages do
    resources :traits, only: [:new, :create]
  end

  resources :tirages, only: [:edit] do
    member do
      patch :set_hexagramme
    end
  end

  resources :hexagrammes

end



# resources :tirages, only: [:new, :create, :edit, :update] do
#   member do
#     patch :set_jet1, :set_jet2, :set_jet3, :set_jet4, :set_jet5, :set_jet6, :set_hexagramme
#   end
# end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hex_answer.rb
class HexAnswer < ApplicationRecord
  belongs_to :hexagramme
end

app/models/hex_perspective.rb
class HexPerspective < ApplicationRecord
  belongs_to :hexagramme
end

app/models/hexagramme.rb
class Hexagramme < ApplicationRecord
end

app/models/tirage.rb
class Tirage < ApplicationRecord
  belongs_to :user
  belongs_to :hexagramme
  has_many :traits
end

app/models/trait.rb
class Trait < ApplicationRecord
  belongs_to :tirage
end

app/models/trigramme.rb
class Trigramme < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tirages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def authenticate_admin!
    authenticate_user!
    redirect_to :somewhere, status: :forbidden unless current_user.admin?
  end
end

app/controllers/hexagrammes_controller.rb
class HexagrammesController < ApplicationController
  before_action :must_be_admin, only: [:edit, :update]
  before_action :set_hex, only: [:edit, :update, :show]

  def index
    @hexagrammes = Hexagramme.all
  end

  def show
  end

  def edit
  end

  def update
    @hexagramme.update(hex_params)
    redirect_to hexagramme_path(@hexagramme)
  end

  private

  def must_be_admin
    unless current_user && current_user.admin?
      redirect_to root_path, notice: "Must be admin"
    end
  end

  def set_hex
    @hexagramme = Hexagramme.find(params[:id])
  end

  def hex_params
    params.require(:hexagramme).permit(
    :numero,
    :nom,
    :description,
    :jugement,
    :jugement_description,
    :trait1,
    :trait1_description,
    :trait2,
    :trait2_description,
    :trait3,
    :trait3_description,
    :trait4,
    :trait4_description,
    :trait5,
    :trait5_description,
    :trait6,
    :trait6_description,
    :grande_image,
    :dixieme_aile,
    :nucleaire,
    :oppose,
    :renverse,
    :image
      )
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/tirages_controller.rb
class TiragesController < ApplicationController
  before_action :set_tirage, only: [:edit, :show, :set_hexagramme]

  def index
    if params[:query].present?
      # sql_query = " \
      # tirages.question ILIKE :query \
      # "
      # @tirages = Tirage.where(sql_query, query: "%#{params[:query]}%")
      @tirages = Tirage.where("question ILIKE ?", "%#{params[:query]}%")
    else
      @tirages = Tirage.all.order("created_at DESC")
    end
  end

  def new
    @tirage = Tirage.new
  end

  def create
    @tirage = Tirage.new(tirage_params)
    @tirage.user = current_user
    if @tirage.save(validate: false)
      redirect_to edit_tirage_path(@tirage)
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def set_hexagramme
    trig_bas = TrigName.call([@tirage.traits[0].nom, @tirage.traits[1].nom, @tirage.traits[2].nom])
    trig_haut = TrigName.call([@tirage.traits[3].nom, @tirage.traits[4].nom, @tirage.traits[5].nom])
    hexrep = SetHexagramme.call(trig_bas, trig_haut)
    @tirage.hexagramme = Hexagramme.find_by nom: hexrep
    @tirage.reply_traits = StringifyTraits.call(@tirage.traits)
    @tirage.perspective = SetPerspective.call(@tirage.reply_traits.split(', '))
    @tirage.save
    redirect_to tirage_path(@tirage)
  end

  private

  def tirage_params
    params.require(:tirage).permit(:question)
  end

  def set_tirage
    @tirage = Tirage.find(params[:id])
  end
end

app/controllers/traits_controller.rb
class TraitsController < ApplicationController
  before_action :set_tirage, only: [:new, :create]
  def new
    @trait = Trait.new
  end

  def create
    @trait = Trait.new
    @trait.tirage = @tirage
    @trait.jet_brut = PerformLancer.call.join(' ')
    @trait.nom = SetTrait.call(@trait.jet_brut.split(' ')).join(' ')
    @trait.save
    redirect_to tirage_path(@trait.tirage)
  end

  private

  def set_tirage
    @tirage = Tirage.find(params[:tirage_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hexagrammes/edit.html.erb
<%= simple_form_for(@hexagramme) do |f| %>
<div class="form-group">
  <%#= f.label :nom %>
  <%= f.input :nom, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.text_field :description, class: 'form-control', placeholder: @hexagramme.description %>
</div>

<div class="form-group">
  <%= f.label :jugement %>
  <%= f.text_field :jugement, class: 'form-control', placeholder: @hexagramme.jugement %>
</div>

<div class="form-group">
  <%= f.label :jugement_description %>
  <%= f.text_field :jugement_description, class: 'form-control', placeholder: @hexagramme.jugement_description %>
</div>

<div class="form-group">
  <%= f.label :trait1 %>
  <%= f.text_field :trait1, class: 'form-control', placeholder: @hexagramme.trait1 %>
</div>

<div class="form-group">
  <%= f.label :trait1_description %>
  <%= f.text_field :trait1_description, class: 'form-control', placeholder: @hexagramme.trait1_description %>
</div>

<div class="form-group">
  <%= f.label :trait2 %>
  <%= f.text_field :trait2, class: 'form-control', placeholder: @hexagramme.trait2 %>
</div>

<div class="form-group">
  <%= f.label :trait2_description %>
  <%= f.text_field :trait2_description, class: 'form-control', placeholder: @hexagramme.trait2_description %>
</div>

<div class="form-group">
  <%= f.label :trait3 %>
  <%= f.text_field :trait3, class: 'form-control', placeholder: @hexagramme.trait3 %>
</div>

<div class="form-group">
  <%= f.label :trait3_description %>
  <%= f.text_field :trait3_description, class: 'form-control', placeholder: @hexagramme.trait3_description %>
</div>

<div class="form-group">
  <%= f.label :trait4 %>
  <%= f.text_field :trait4, class: 'form-control', placeholder: @hexagramme.trait4 %>
</div>

<div class="form-group">
  <%= f.label :trait4_description %>
  <%= f.text_field :trait4_description, class: 'form-control', placeholder: @hexagramme.trait4_description %>
</div>

<div class="form-group">
  <%= f.label :trait5 %>
  <%= f.text_field :trait5, class: 'form-control', placeholder: @hexagramme.trait5 %>
</div>

<div class="form-group">
  <%= f.label :trait5_description %>
  <%= f.text_field :trait5_description, class: 'form-control', placeholder: @hexagramme.trait5_description %>
</div>

<div class="form-group">
  <%= f.label :trait6 %>
  <%= f.text_field :trait6, class: 'form-control', placeholder: @hexagramme.trait6 %>
</div>

<div class="form-group">
  <%= f.label :trait6_description %>
  <%= f.text_field :trait6_description, class: 'form-control', placeholder: @hexagramme.trait6_description %>
</div>

<div class="form-group">
  <%= f.label :numero %>
  <%= f.text_field :numero, class: 'form-control', placeholder: @hexagramme.numero %>
</div>

<div class="form-group">
  <%= f.label :grande_image %>
  <%= f.text_field :grande_image, class: 'form-control', placeholder: @hexagramme.grande_image %>
</div>

<div class="form-group">
  <%= f.label :dixieme_aile %>
  <%= f.text_field :dixieme_aile, class: 'form-control', placeholder: @hexagramme.dixieme_aile %>
</div>

<div class="form-group">
  <%= f.label :nucleaire %>
  <%= f.text_field :nucleaire, class: 'form-control', placeholder: @hexagramme.nucleaire %>
</div>

<div class="form-group">
  <%= f.label :oppose %>
  <%= f.text_field :oppose, class: 'form-control', placeholder: @hexagramme.oppose %>
</div>

<div class="form-group">
  <%= f.label :renverse %>
  <%= f.text_field :renverse, class: 'form-control', placeholder: @hexagramme.renverse %>
</div>

<div class="form-group">
  <%= f.label :image %>
  <%= f.text_field :image, class: 'form-control', placeholder: @hexagramme.image %>
</div>

<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/hexagrammes/index.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <div class="maintitle open-font">
          <h4>LES HEXAGRAMMES</h4>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <div class="hex-list">
              <% @hexagrammes.each do |hex| %>
    <%= link_to hexagramme_path(hex) do %>
          <div class="hex-img">
            <%= image_tag "#{hex.numero}.jpg" %>
      <%= hex.nom %>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hexagrammes/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <div class="maintitle open-font">
          <h4><%= @hexagramme.nom %></h4>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <div class="jugement">
          <%= @hexagramme.jugement %>
        </div>
        <div class="jugement">
          <%= @hexagramme.trait1 %>
        </div>
        <div class="jugement">
          <%= @hexagramme.trait2 %>
        </div>
        <div class="jugement">
          <%= @hexagramme.trait3 %>
        </div>
        <div class="jugement">
          <%= @hexagramme.trait4 %>
        </div>
        <div class="jugement">
          <%= @hexagramme.trait5 %>
        </div>
        <div class="jugement">
          <%= @hexagramme.trait6 %>
        </div>
        <div class="jugement">
          <h4>Grande Image</h4>
          <%= @hexagramme.grande_image %>
        </div>
        <div class="jugement">
          <h4>Dixième Aile</h4>
          <%= @hexagramme.dixieme_aile %>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <div class="jugement">
          <h4>Jugement</h4>
          <%= @hexagramme.jugement %>
        </div>
        <div class="description">
          <%= @hexagramme.jugement_description %>
        </div>
        <div class="jugement">
          <%= @hexagramme.trait1 %>
        </div>
        <div class="description">
          <%= @hexagramme.trait1_description %>
        </div>
        <div class="jugement">
          <%= @hexagramme.trait2 %>
        </div>
        <div class="description">
          <%= @hexagramme.trait2_description %>
        </div>
        <div class="jugement">
          <%= @hexagramme.trait3 %>
        </div>
        <div class="description">
          <%= @hexagramme.trait3_description %>
        </div>
        <div class="jugement">
          <%= @hexagramme.trait4 %>
        </div>
        <div class="description">
          <%= @hexagramme.trait4_description %>
        </div>
        <div class="jugement">
          <%= @hexagramme.trait5 %>
        </div>
        <div class="description">
          <%= @hexagramme.trait5_description %>
        </div>
        <div class="jugement">
          <%= @hexagramme.trait6 %>
        </div>
        <div class="description">
        <%= @hexagramme.trait6_description %>
        </div>
      </div>
    </div>
  <% if current_user.admin == true %>
    <%= link_to edit_hexagramme_path(@hexagramme) do %>
      <div class="large-btn">Edit</div>
    <% end %>
    <% end %>
  </div>

<!--     t.integer "numero"
    t.string "nom"
    t.text "grande_image"
    t.text "dixieme_aile"
    t.text "nucleaire"
    t.text "oppose"
    t.text "renverse"
    t.string "image" -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag %>
    <title>Ask Uncle Li</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="wrapper homepage" style="background-image: linear-gradient(rgba(255,255,255,0.5),rgba(255,255,255,0.4)), url(<%= image_path 'homepage.jpg'%>);">
  <%= link_to new_tirage_path do %>

  <div class="large-btn">Nouveau</br> tirage</div>

  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "zhouyi.png" %>
    <% end %>
  <div class="navbar-title">
    <!-- <h4>Ask Uncle Li</h4> -->
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Nouveau tirage", new_tirage_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mes tirages", tirages_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Hexagrammes", hexagrammes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
        <!-- <li class="nav-item dropdown">
          <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          </div>
        </li> -->
    </ul>
  </div>
</div>

app/views/tirages/edit.html.erb
<div class="wrapper">
  <div class="white-bubble">
    <div class="maintitle">
      <h4><%= @tirage.question %></h4>
    </div>
    <div class="lancer-btn btn-active">
      <%= render partial: 'traits/bouton', locals: {
        tirage: @tirage, trait: Trait.new } %>
        <%#= link_to 'Lancer 6', set_jet6_tirage_path(@tirage), method: :patch %>
    </div>
    <div class="lancer-btn btn-active">
      <%= render partial: 'traits/bouton', locals: {
        tirage: @tirage, trait: Trait.new } %>
        <%#= link_to 'Lancer 5', set_jet5_tirage_path(@tirage), method: :patch %>
    </div>
    <div class="lancer-btn btn-active">
      <%= render partial: 'traits/bouton', locals: {
        tirage: @tirage, trait: Trait.new } %>
        <%#= link_to 'Lancer 4', set_jet4_tirage_path(@tirage), method: :patch %>
    </div>
    <div class="lancer-btn btn-active">
      <%= render partial: 'traits/bouton', locals: {
        tirage: @tirage, trait: Trait.new } %>
        <%#= link_to 'Lancer 3', set_jet3_tirage_path(@tirage), method: :patch %>
    </div>
    <div class="lancer-btn btn-active">
      <%= render partial: 'traits/bouton', locals: {
        tirage: @tirage, trait: Trait.new } %>
        <%#= link_to 'Lancer 2', set_jet2_tirage_path(@tirage), method: :patch %>
    </div>

    <div class="lancer-btn btn-active">
      <%= render partial: 'traits/bouton', locals: {
        tirage: @tirage, trait: Trait.new } %>
    </div>
    <div class="lancer-btn btn-active">
      <%= link_to 'résultat', set_hexagramme_tirage_path(@tirage), method: :patch %>
    </div>
  </div>
</div>

app/views/tirages/explanation_toggle.js.erb
function showParagraph(e) {
  console.log(e);
  const explanation = document.querySelectorAll(".explanation");
  console.log(explanation);
  if(explanation.style.display === "none") {
    explanation.style.display = "block";
  } else {
    explanation.style.display = "none";
  }
}

const texteBtn = document.querySelectorAll('.texte-btn');
texteBtn.forEach(tb => tb.addEventListener('click', showParagraph));
// texteBtn.addEventListener('click', showParagraph);


// faut que je puisse chercher dans le div cliqué
// le nom du texte en display
// pour que ça permette d'afficher le paragraphe correspondant
// avec _description

app/views/tirages/index.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <div class="maintitle open-font">
          <h4>MES TIRAGES</h4>
        </div>
                <div>
          <%= form_tag tirages_path, method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control form-control-sm search-layout",
            placeholder: "Chercher un tirage"
            %>
            <% end %>
        </div>
      </div>
    </div>
    <% @tirages.each do |tirage| %>
      <% if tirage.user == current_user %>
        <div class="row justify-content-center">
          <div class="col-12 col-lg-6">
            <div class="list-item">
              <div class="list-text">
                <%= link_to tirage_path(tirage) do %>
                <div class="list-tirage">
                  <%= tirage.question %>
                </div>
                <% end %>
                <div class="list-hex">
                  <%= tirage.hexagramme.nom %> /
                  <%= tirage.perspective %>
                </div>
              </div>
              <div class="list-date">
                <%= tirage.created_at.strftime("%d/%m/%y") %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tirages/new.html.erb
<div class="wrapper">
  <div class="bag">
    <div class="titlearea">
    <div class="open-font">
      <h4>Quelle est la question ?</h4>
    </div>
    </div>
    <div class="formarea">
    <div class="question-form">
      <%= simple_form_for @tirage, url: tirages_path do |f| %>
      <%= f.text_area :question, label: false, placeholder: "I...", id: "question-form" %>
      <!-- <div class="post-creation-buttons"> -->
        <%#= f.submit 'Preview',  class: "btn-karma" %>
    </div>
    </div>
    <div class="buttonarea">
      <%= f.submit 'ok', class: "normal-btn" %>
      </div>
      <!-- </div> -->
      <% end %>
  </div>
</div>

app/views/tirages/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <div class="maintitle open-font">
          <h4><%= @tirage.question %></h4>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <div class="tirage-hex">
          <% arr_img = @tirage.reply_traits.split(', ') %>
          <div>
            <%= image_tag "#{arr_img[5]}.jpg", class:"img-traits" %>
          </div>
          <div>
            <%= image_tag "#{arr_img[4]}.jpg", class:"img-traits" %>
          </div>
          <div>
            <%= image_tag "#{arr_img[3]}.jpg", class:"img-traits" %>
          </div>
          <div>
            <%= image_tag "#{arr_img[2]}.jpg", class:"img-traits" %>
          </div>
          <div>
            <%= image_tag "#{arr_img[1]}.jpg", class:"img-traits" %>
          </div>
          <div>
            <%= image_tag "#{arr_img[0]}.jpg", class:"img-traits" %>
          </div>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <%= link_to hexagramme_path(@tirage.hexagramme.id)  do %>
        <div class="open-font hex-nom">
          <h4> <%= @tirage.hexagramme.nom %></h4>
        </div>
        <% end %>
        <div class="jugement jugement-btn">
          <h4>Jugement</h4>
          <%= @tirage.hexagramme.jugement %>
        </div>
        <div class="description explanation" style="display: none;">
          <%= @tirage.hexagramme.jugement_description %>
        </div>
        <% @tirage.traits.each_with_index do |trait, i| %>
        <% if trait.nom.include? 'mutant' %>
        <% cn = "trait" + (i + 1).to_s %>
        <div class="jugement trait-btn" id="<%= cn %>">
          <%= @tirage.hexagramme["trait" + (i + 1).to_s] %>
        </div>
        <div class="description" id="<%= cn %>_description" style="display: none;">
          <%= @tirage.hexagramme["trait" + (i + 1).to_s + "_description"] %>
        </div>
        <% end %>
        <% end %>
        <div class="open-font hex-nom perspective">
          <h4>PERSPECTIVE</h4>
        </div>
        <div class="open-font hex-nom">
          <h4> <%= @tirage.perspective %></h4>
          <% h = Hexagramme.find_by nom: "#{@tirage.perspective}" %>
        </div>
        <div class="jugement">
          <%= h.jugement %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<script>
  function showJugement(e) {
    console.log(e);
    console.log(e.toElement.className);
  const explanation = document.querySelector(".explanation");
  console.log(explanation.className);
  if(explanation.style.display === "none") {
    explanation.style.display = "block";
  } else {
    explanation.style.display = "none";
  }
}

function showTrait(e) {
  console.log(e.toElement.id);
  const description = document.getElementById(`${e.toElement.id}_description`);
  console.log(description);
  if(description.style.display === "none") {
    description.style.display = "block"
  } else {
    description.style.display = "none";
  }
}

const jugementBtn = document.querySelector('.jugement-btn');
jugementBtn.addEventListener('click', showJugement);

const traitsBtn = document.querySelectorAll('.trait-btn');
traitsBtn.forEach(trait => trait.addEventListener('click', showTrait));

</script>

app/views/traits/_bouton.html.erb
<%= form_for([tirage, trait], remote: true) do |f| %>
<div class="lancer-btn btn-active">
  <%= f.submit "Lancer 1" %>
</div>
<% end %>